In [1]:
1

1

In [6]:
import pandas as pd

In [7]:
data = pd.read_excel("project2_delivery_data.xlsx")
data

,Distance_km,Item_Count,Traffic_Level,Active_Courier_Orders,Delivery_Time_min
0,8.7,9,10,6,66.3
1,2.0,11,10,10,55.5
2,6.1,15,1,7,46.8
3,3.6,14,9,0,49.4
4,6.1,10,2,19,46.9
...,...,...,...,...,...
995,0.7,10,5,5,29.7
996,6.8,15,9,4,52.6
997,13.2,7,9,13,77.9
998,4.6,14,3,0,35.0
999,2.5,10,6,1,44.8

In [9]:
data.columns

Index(['Distance_km', 'Item_Count', 'Traffic_Level', 'Active_Courier_Orders',
       'Delivery_Time_min'],
      dtype='str')

In [10]:

x=data[['Distance_km', 'Item_Count', 'Traffic_Level', 'Active_Courier_Orders']]
y=data['Delivery_Time_min']
y

0      66.3
1      55.5
2      46.8
3      49.4
4      46.9
       ...
995    29.7
996    52.6
997    77.9
998    35.0
999    44.8
Name: Delivery_Time_min, Length: 1000, dtype: float64

In [9]:
x=data[['screen_brightness', 'internet_usage_min', 'gaming_usage_min']]
y=data['battery_hours']
y

KeyError: "None of [Index(['screen_brightness', 'internet_usage_min', 'gaming_usage_min'], dtype='str')] are in the [columns]"

In [11]:
from sklearn.linear_model import LinearRegression
import numpy as np

In [12]:
from sklearn.model_selection import train_test_split

x_test,x_train,y_test,y_train=train_test_split(x,y,test_size=0.3)

In [13]:
x_test

     Distance_km  Item_Count  Traffic_Level  Active_Courier_Orders
390         15.6          14              9                      1
219          7.1           8              1                      0
583          9.5          13              7                      0
597         10.3          11              6                      7
756         11.6           3              6                     13
..           ...         ...            ...                    ...
532          7.1           3              8                     11
547          1.8          15             10                     19
639          4.0          10             10                      6
670          4.8          11              1                     19
57           5.6           9              4                      8

[700 rows x 4 columns]

In [22]:
y_test

390    77.4
219    26.5
583    64.7
597    61.5
756    65.4
       ...
532    64.7
547    56.8
639    42.2
670    44.5
57     46.0
Name: Delivery_Time_min, Length: 700, dtype: float64

In [13]:
model = LinearRegression()

model.fit(x_train,y_train)

LinearRegression()

In [15]:
model.predict(np.array([15.6,14.0,9,1.0]).reshape(1,-1))

c:\Users\Bashir-Rayaneh\Desktop\cat_dog\cool\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([76.68303011])

In [21]:
y_test

390    77.4
219    26.5
583    64.7
597    61.5
756    65.4
       ...
532    64.7
547    56.8
639    42.2
670    44.5
57     46.0
Name: Delivery_Time_min, Length: 700, dtype: float64

In [20]:
model.predict(x_test)

array([ 76.74584276,  35.70512294,  56.65549667,  61.20978284,
        64.17196809,  39.43197681,  43.14072241,  57.50285986,
        23.28141531,  40.54564575,  56.41211621,  73.17610597,
        25.62931544,  56.2690047 ,  54.18798748,  45.46938895,
        47.15321727,  56.33850093,  64.51038948,  25.95689499,
        84.75699408,  84.46129725,  70.49742587,  81.33981751,
        34.60967923,  36.01518501,  49.84081323,  52.31761432,
        48.32366767,  60.45580626,  64.89410839,  38.43984779,
        51.21527849,  69.86161176,  55.58531625,  30.20064144,
       100.31692587,  67.61980426,  60.40301712,  35.9971232 ,
        59.9621899 ,  56.06647972,  42.50987829,  52.49086621,
        57.52898557,  48.34754828,  59.90460395,  51.55322711,
        51.77390363,  46.83974492,  54.90735858,  36.45157995,
        36.03526569,  43.69453437,  45.63162582,  54.03285258,
        89.28969504,  57.87258468,  47.73774677,  50.8396748 ,
        43.82995313,  58.62934409,  69.27232702,  52.53819622,
        32.15028912,  44.79564708,  41.06729845,  64.7387123 ,
        41.33814085,  33.81376022,  69.02098601,  76.58772005,
        52.45016052,  42.55303895,  86.60491473,  49.29805786,
        58.06959534,  67.49837257,  68.6432919 ,  47.64147887,
        42.89386012,  56.40035574,  57.25654189, 109.99395193,
        66.8979782 ,  44.5893358 ,  33.53886158,  82.41149759,
        49.19784409,  52.37718246,  40.06378987,  58.8652001 ,
        45.3578508 ,  39.22796581,  45.24977598,  52.40084833,
        65.49375732,  44.00709785,  73.40575842,  41.17344414,
        62.3221117 ,  67.60917889,  52.00339652,  45.03133968,
        58.67448205,  70.98419656,  55.37206641,  39.20221612,
        71.65398382,  65.04225168,  34.87262115,  60.15472184,
        80.73867066,  48.85403023,  61.91034282,  62.71369338,
        35.01130039,  37.25977866,  63.97115262,  82.36495947,
        37.74922566,  48.83517266,  42.24810816,  56.23577213,
        49.52996415,  66.17396882,  49.80497102,  77.1257153 ,
        74.8282527 ,  72.11393639,  35.16925968,  43.40681171,
        78.00593674,  55.42472882,  54.3128825 ,  73.88174418,
        61.07676386,  56.50378354,  31.56089614,  63.49876567,
        78.06133553,  67.00568359,  55.75563064,  64.91275122,
        62.14715903,  59.1631836 ,  60.55971172,  51.97796981,
        48.29043511,  51.48692153,  50.96441514,  46.35328847,
        60.04019101,  59.12632428,  48.10848697,  66.18326945,
        82.60920725,  74.54757682,  51.73004396,  45.25329938,
        80.42034357,  58.8000279 ,  49.23448866,  47.69057144,
        62.48793376,  46.33085446,  45.96150566,  57.47300089,
        47.99875783,  81.35872813,  70.40575854,  45.81988891,
        58.63666253,  51.211437  ,  38.93757343,  57.23570214,
        44.54168281,  45.12194346,  59.12284733,  39.98344203,
        51.50978504,  69.07910095,  48.54114378,  72.76807523,
        44.025586  ,  90.3834893 ,  41.52260401,  52.36842616,
        36.43827827,  68.2507549 ,  67.96736286,  59.07321703,
        49.63124147,  52.76656549,  39.94119025,  70.7988661 ,
        44.59942833,  42.2672384 ,  68.29098293,  53.33314629,
        33.05946066,  58.57379062,  39.06246845,  56.3067111 ,
        47.80077824,  40.70601355,  56.60710311,  34.66262305,
        55.7022556 ,  46.82659792,  40.3850632 ,  61.29408528,
        48.38670788,  67.70030677,  62.8170594 ,  40.46021969,
        50.84427537,  45.33931621,  57.11523938,  43.03729461,
        40.27698838,  48.2575304 ,  46.41024209,  52.99900248,
        66.95765457,  67.49041691,  38.67201699,  46.69860197,
        44.38959365,  57.85212797,  63.47669406,  50.67791559,
        59.1886103 ,  58.49894349,  86.49342963,  48.884157  ,
        61.70446763,  31.30036274,  38.61143174,  77.95588397,
        59.96678173,  65.9717717 ,  62.81032197,  66.58734558,
        43.97980208,  37.53244368,  36.70324394,  40.80874235,
        69.00553872,  45.51287746,  53.74256844,  31.65577751,
       100.04784602,  51.20197681,  52.89953417,  81.09606274,
        39.82483679,  65.45332816,  31.63691994,  40.68293358,
        79.5742035 ,  93.41623433,  66.92394435,  54.35701697,
        73.30703942,  65.98891489,  52.01717586,  43.51295739,
        45.25693101,  72.66144701,  45.95781396,  81.41690486,
        39.06716851,  48.50717064,  44.44130074,  67.27095862,
        46.13688466,  70.20297065,  40.48886043,  36.21540482,
        41.16644379,  57.94363188,  71.54254029,  75.78634679,
        46.30510477,  60.39885264,  58.908675  ,  74.02874851,
        64.22329915,  33.70307576,  24.59081661,  66.41970089,
        59.35441702,  79.45288706,  46.29073466,  39.28208142,
        37.62186591,  50.43709832,  57.58823073,  42.42125182,
        34.26725678,  48.5186497 ,  34.02354846,  63.3758944 ,
        54.00790354,  57.31022629,  61.43319574,  44.04486604,
        44.13643002,  46.78711534,  46.89065137,  65.10501536,
        40.54975504,  37.659316  ,  80.19565238,  35.55801037,
        43.95859117,  43.84160537,  58.42211905,  53.18207911,
        56.99177734,  45.1057556 ,  58.71968007,  60.5212927 ,
        57.70426121,  69.4137842 ,  47.83705166,  73.99802223,
        39.29394352,  57.11341676,  62.04256116,  40.72407049,
        35.58482849,  54.45931628,  91.61056547,  55.62404463,
        41.35224318,  26.95831976,  44.99874921,  58.25849564,
        40.77364559,  89.74708442,  52.38509168,  46.97735573,
        59.0078804 ,  36.74929565,  55.86888318,  66.37445642,
        41.72677843,  53.74626013,  68.71214705,  55.62997655,
        49.62467721,  62.99510811,  40.19023098,  64.06753852,
        59.04602289,  50.04531551,  55.92951487,  59.04597645,
        76.71075088,  48.29075809,  50.51637772,  43.54820883,
        53.14105044,  39.40991394,  40.76925977,  38.52569144,
        53.62269158,  32.1891858 ,  65.09550487,  63.68722115,
        34.67255602,  49.68418529,  44.70504331,  35.94450723,
        40.73053138,  32.48930128,  54.83833513,  56.07251815,
        48.58376499,  51.37966097,  52.0483798 ,  47.32971603,
        46.30542775,  54.57282513,  73.66089936,  46.84465973,
        31.28903836,  49.75250974,  49.19335176,  56.72665211,
        49.6950872 ,  50.90591543,  34.46779083,  56.45714593,
        46.46322748,  36.3678634 ,  54.26208916,  34.69504522,
        90.94504218,  50.92488612,  56.30725055,  34.16255068,
        72.98010196,  68.22848216,  65.5104829 ,  42.05066629,
        26.23516235,  59.66725703,  50.25210445,  50.30135658,
        23.35871741,  41.85124712,  65.38965073,  54.38740665,
        71.64772893,  98.94027729,  42.41708246,  72.05315002,
        52.36714298,  63.4756857 ,  53.2240631 ,  49.98666112,
        32.70623794,  52.49347586,  82.70428974,  52.71843484,
        71.70553623,  77.79971835,  45.84526043,  58.08471964,
        57.76863277,  65.36918528,  56.06514838,  62.67425725,
        42.78108524,  42.50538596,  65.15363515,  65.78164828,
        67.5827302 ,  38.53382028,  60.6080501 ,  57.93690807,
        35.71992427,  54.94395498,  37.69965055,  58.69938464,
        46.74651788,  54.06218745,  62.53557801,  46.99631768,
        64.5919091 ,  72.29390722,  44.56069994,  47.63180881,
        56.02946573,  58.17307833,  62.62084451,  64.24142275,
        72.23146652,  63.35446875,  46.77589919,  56.90251853,
        63.53167038,  57.92921532,  56.97019701,  49.90551265,
        64.43015476,  41.00714442,  41.4812611 ,  85.64121658,
        48.33060135,  55.25116756,  65.63516806,  37.39306543,
        59.21894693,  40.33714242,  24.27429852,  44.41604234,
        60.90272007,  50.75976307,  56.73845415,  57.99710855,
        54.3674276 ,  83.46132568,  45.31265277,  46.12982913,
        89.41768224,  30.88283024,  64.5623731 ,  52.47067242,
        49.77874368,  52.45657009,  93.06964253,  35.75929862,
        44.67640745,  64.71728666,  62.52409895,  43.18222875,
        85.79516993,  46.90907773,  53.6136057 ,  41.29914467,
        67.78215425,  69.22349736,  48.24849756,  54.97472283,
        51.31229673,  57.53983229,  59.20404397,  49.65971879,
        89.17120959,  51.78239702,  27.02247973,  38.26168596,
        55.18914933,  64.60622617,  54.18735026,  46.74134016,
        49.18198093,  43.53736699,  93.65327189,  59.87389129,
        38.40522869,  33.43858775,  55.73388201,  45.93457931,
        37.66700875,  37.98999648,  72.7333479 ,  25.31188848,
        70.91037142,  49.86528462,  38.26884973,  63.08934352,
        26.90724989,  43.29184966,  51.83362645,  62.29470769,
        41.99478984,  31.93602217,  53.08212826,  48.19022134,
        43.11491968,  46.13902152,  67.4093285 ,  35.58680579,
        65.50251362,  93.00324722,  63.77847088,  65.84141755,
        39.9589242 ,  39.82163637,  66.7620769 ,  44.10752636,
        48.21104747,  34.47009111,  38.72265565,  47.67406933,
        56.52738762,  32.58572386,  33.58795415,  33.87161398,
        47.7498166 ,  70.53839276,  59.35239327,  45.88398882,
        42.48119111,  49.99231162,  69.21575156,  41.85290144,
        66.46169149,  57.17250724,  46.5334276 ,  53.78755172,
        60.36653383,  72.17804504,  97.42456471,  60.06427762,
        40.45776473,  37.74478851,  61.89747235,  36.63785212,
        61.81610741,  63.17049199,  83.17130273,  32.74016463,
        48.38760802,  48.34845716,  53.81148366,  68.92449676,
        47.60376758,  54.26758498,  71.47903603,  55.63943186,
        49.12951965,  65.21548996,  87.33070028,  56.75881624,
        61.7568158 ,  50.89876041,  50.42946076,  53.31936695,
        38.99633606,  48.26079088,  75.36353007,  52.84306695,
        71.36391442,  57.01042017,  65.77967098,  55.70712396,
        71.10561951,  67.94930105,  60.95764119,  55.98645975,
        35.34159782,  65.46100729,  65.30187134,  50.74383812,
        82.13045228,  46.94769789,  58.22376343,  65.18103916,
        40.96360946,  51.97738392,  43.37171495,  27.65247017,
        60.11936217,  42.25190809,  51.06132514,  50.68706154,
        40.6771099 ,  54.34382352,  52.77495725,  48.25325281,
        69.07584047,  36.19152421,  40.59522086,  51.68286863,
        32.73220409,  38.8852155 ,  41.6608056 ,  45.32434658,
        31.73686591,  45.99521101,  44.56577817,  79.35989011,
        68.23339209,  55.64403242,  62.01500248,  33.23671361,
        49.81095426,  53.11840168,  44.3472818 ,  43.46081908,
        98.66937971,  34.74264303,  70.83237032,  36.47235964,
        32.29126864,  72.94906145,  44.13317441,  51.31442871,
        65.02430299,  52.05143041,  64.43197251,  62.38466551,
        35.49742513,  53.71687394,  40.20428685,  36.55676371,
        59.39048931,  61.0065173 ,  57.25274196,  59.23240817,
        59.39929206,  31.99109798,  54.68175364,  53.20318178,
        54.36727292,  51.17622713,  71.65489757,  66.36693197,
        55.11964822,  42.74049266,  56.75849327,  85.41406554,
        32.19879579,  40.19344501,  45.23876584,  58.56977594,
        57.53246252,  63.25264883,  47.70119681,  55.67239663,
        61.59527793,  52.56709987,  48.27157753,  45.51394102])

In [17]:
y_test

6       6.02
119     4.99
41     14.95
128     3.58
190     6.43
       ...
178    12.01
140    15.10
9       5.33
17      6.51
67     14.28
Name: battery_hours, Length: 140, dtype: float64

In [1]:
t=np.array([1,2,6,8])
p=np.array([1,3,6.8,10])

MAE= np.mean(np.abs(p-t))
MSE= np.mean(np.square(p-t))
RMSE=np.sqrt(np.mean(np.square(p-t)))

MAE,MSE,RMSE

NameError: name 'np' is not defined

int